### ISSUE TITLE
No module named 'correlation_cuda'

### ISSUE THREAD

**Issue by Ouya-Bytes** [BlarkLee/MonoPLFlowNet#1]
When I evaluate scene flow, I have get the Error: 
Traceback (most recent call last):
  File "tools/monopl_main_semi_flyingthings3d.py", line 18, in <module>
    import models
  File "/workspace/MonoPLFlowNet/flow/tools/../models/__init__.py", line 6, in <module>
    from .MonoSceneFlow_fly import *
  File "/workspace/MonoPLFlowNet/flow/tools/../models/MonoSceneFlow_fly.py", line 8, in <module>
    from ablation_MonoSceneFlow_utils.correlation_package.correlation import Correlation
  File "/workspace/MonoPLFlowNet/flow/models/ablation_MonoSceneFlow_utils/correlation_package/correlation.py", line 4, in <module>
    import correlation_cuda
ModuleNotFoundError: No module named 'correlation_cuda'.

I exec "python3 setup build" to compile, but failure.
Can you give some suggestion, thanks!

**Comment by NickiJQ** [comment]
I have the same problem, can you give some suggestion, thanks!
